Update ntldr.h,ntrtl.h
winsiderss/systeminformer pull request #1451
Opened 2022-10-25 05:55 UTC by MiroKaku

2022-10-25 06:00 UTC, MiroKaku commented
I have read the CLA Document and I hereby sign the CLA

2022-10-25 17:07 UTC, jxy-s requested changes
I confirmed the additions and corrections myself. Please make the formatting adjustments.

2022-10-25 17:07 UTC, jxy-s commented on phnt/include/ntldr.h
> +);
```suggestion
    );
```

2022-10-25 17:07 UTC, jxy-s commented on phnt/include/ntrtl.h
> +);
```suggestion
    );
```

2022-10-25 17:07 UTC, jxy-s commented on phnt/include/ntrtl.h
> +);
```suggestion
    );
```

2022-10-26 05:46 UTC, jxy-s approved these changes

2022-10-26 05:46 UTC, merged