fix: NtConvertBetweenAuxiliaryCounterAndPerformanceCounter definition
winsiderss/systeminformer pull request #1927
Opened 2023-12-11 06:36 UTC by MiroKaku

ida -> kernelbase.dll

```C
HRESULT __stdcall ConvertAuxiliaryCounterToPerformanceCounter(
        ULONGLONG ullAuxiliaryCounterValue,
        PULONGLONG lpPerformanceCounterValue,
        PULONGLONG lpConversionError)
{
  NTSTATUS Status; // eax
  HRESULT result; // eax
  ULONGLONG v5; // [rsp+30h] [rbp+8h] BYREF

  v5 = ullAuxiliaryCounterValue;
  LOBYTE(ullAuxiliaryCounterValue) = 1;
  Status = NtConvertBetweenAuxiliaryCounterAndPerformanceCounter(
             ullAuxiliaryCounterValue,
             &v5,
             lpPerformanceCounterValue,
             lpConversionError);
  if ( Status == STATUS_NOT_SUPPORTED )
    return E_NOTIMPL;
  if ( Status == STATUS_INVALID_PARAMETER )
    return 0x8000000B;
  result = RtlNtStatusToDosErrorNoTeb(Status);
  if ( result > 0 )
    return (unsigned __int16)result | 0x80070000;
  return result;
}
```

```C
HRESULT __stdcall ConvertPerformanceCounterToAuxiliaryCounter(
        ULONGLONG ullPerformanceCounterValue,
        PULONGLONG lpAuxiliaryCounterValue,
        PULONGLONG lpConversionError)
{
  NTSTATUS Status; // eax
  HRESULT result; // eax
  ULONGLONG v5; // [rsp+30h] [rbp+8h] BYREF

  v5 = ullPerformanceCounterValue;
  Status = NtConvertBetweenAuxiliaryCounterAndPerformanceCounter(0i64, &v5, lpAuxiliaryCounterValue, lpConversionError);
  if ( Status == STATUS_NOT_SUPPORTED )
    return E_NOTIMPL;
  if ( Status == STATUS_INVALID_PARAMETER )
    return 0x8000000B;
  result = RtlNtStatusToDosErrorNoTeb(Status);
  if ( result > 0 )
    return (unsigned __int16)result | 0x80070000;
  return result;
}
```

2023-12-12 19:28 UTC, dmex requested changes

2023-12-12 19:28 UTC, dmex commented on phnt/include/ntexapi.h
> +    _In_ BOOL ConvertAuxiliaryToPerformanceCounter,
byte/boolean?

2023-12-12 19:28 UTC, dmex commented on phnt/include/ntzwapi.h
> +    _In_ BOOL ConvertAuxiliaryToPerformanceCounter,
byte/boolean?

2023-12-13 01:45 UTC, MiroKaku commented on phnt/include/ntexapi.h
> +    _In_ BOOL ConvertAuxiliaryToPerformanceCounter,
Yes, is BOOLEAN

2023-12-13 02:46 UTC, dmex approved these changes

2023-12-13 02:53 UTC, merged

2023-12-13 02:53 UTC, dmex commented
🍺🎄❄️

2023-12-13 03:00 UTC, MiroKaku commented
> 🍺🎄❄️

🍻🎄🎉