Update the prototype of NtCreateIRTimer
winsiderss/systeminformer pull request #2105
Opened 2024-06-20 09:07 UTC by elnx

According to my reverse engineering results, the pseudocode 
 of NtCreateIRTimer syscall is as follows:

```c
NTSTATUS NtCreateIRTimer(PHANDLE TimerHandle, LPVOID Reserved, ACCESS_MASK DesiredAccess) {
  return NtCreateTimer2(TimerHandle, Reserved, 0, 2, DesiredAccess);
}
```

2024-06-22 00:57 UTC, dmex commented
What parameters does this kernel have for NtCreateIRTimer?

[ntoskrnl.zip](https://github.com/user-attachments/files/15934613/ntoskrnl.zip)

![image](https://github.com/winsiderss/systeminformer/assets/1306177/cd36a988-5f7d-4e5a-bfe2-fdafa51287ed)

2024-06-24 06:39 UTC, elnx commented
It looks like this syscall has a different prototype on different version? I reserved this syscall on a win10 ntoskrnl. Maybe a version determination macro is needed here.

2024-06-26 16:57 UTC, dmex requested changes

2024-06-26 16:57 UTC, dmex commented on phnt/include/ntexapi.h
> +    _In_ LPVOID Reserved,
* LPVOID needs to be PVOID
* `PVOID Reserved` would be `HANDLE IRTimerHandle` on Windows 10 and 11?

2024-06-28 23:38 UTC, dmex approved these changes

2024-06-29 00:39 UTC, merged