kph Don't map whole section when looking for mapped file name
winsiderss/systeminformer pull request #2254
Opened 2024-10-25 17:23 UTC by ge0rdi

It is enough to map just first page of section in order to query mapped file name.
Mapping whole section may cause unnecessarily big paged pool usage in case of huge sections.

---

The issue with big pool usage can be easily demonstrated this way:

- Open some project in Visual Studio 2022
- Notice current paged pool size (either in SI or Task Manager)
- In SI press Ctrl+F, enter some string and press enter
- Paged pool size raises by ~20GB

Visual Studio has about 5 processes where each has opened handle to 2TB section. Running search in SI will cause that each such section is mapped (which takes ~4GB of paged pool), but the memory is not freed upon section unmapping. It is freed when given section handle closes (so you need to close Visual Studio in order to reclaim that memory).

This seems to be standard Windows behavior (at least Win10/11). It seems the system caches memory that was allocated for mapping purposes (PTEs) so that it can be immediately reused when section is mapped next time.

2024-10-25 17:30 UTC, ge0rdi commented
I have also noticed that [ObCloseHandle](https://github.com/winsiderss/systeminformer/blob/master/KSystemInformer/object.c#L2059) should be probably done after [KeUnstackDetachProcess](https://github.com/winsiderss/systeminformer/blob/master/KSystemInformer/object.c#L2061).
Do you think I can fix that as well?

2024-10-25 23:18 UTC, jxy-s commented
Nice find @ge0rdi. I think we could do even better. Since we no longer have to support Windows 7 I think there is an ideal way that will almost always reclaim immediately and avoid having to invade the system process. Allow me some time to investigate.

2024-10-26 00:13 UTC, jxy-s requested changes
Nice find @ge0rdi. The kernel is going to complete the accounting for the section if we map the entire thing. Which is why the pool usage jump for very large sections.

> I have also noticed that [ObCloseHandle](https://github.com/winsiderss/systeminformer/blob/master/KSystemInformer/object.c#L2059) should be probably done after [KeUnstackDetachProcess](https://github.com/winsiderss/systeminformer/blob/master/KSystemInformer/object.c#L2061).
Do you think I can fix that as well?

This doesn't technically matter. But for correctness of ordering releasing of resources - yes go ahead and re-order those.

Please conform to the commit message style for kernel driver changes:
`kph all lower case subject`

2024-10-26 06:23 UTC, jxy-s approved these changes

2024-10-26 06:36 UTC, merged

2024-10-26 07:04 UTC, ge0rdi commented
@jxy-s 
Do you have any idea when this could get released?
It is rather annoying issue (though I guess it is much better now that I understand what is causing it).

2024-10-26 15:03 UTC, jxy-s commented
> @jxy-s 
> Do you have any idea when this could get released?
> It is rather annoying issue (though I guess it is much better now that I understand what is causing it).

No, but I'll do what I can to expedite it. Maybe a few weeks. Depends on when we can submit for signing.

2024-10-26 15:56 UTC, ge0rdi commented
Cool, thank you.

> Depends on when we can submit for signing.

What do you mean by that? I guess you can submit driver for attestation signing at any time.
Or is there something you need to wait for?

2024-10-31 17:22 UTC, jxy-s commented
> What do you mean by that? I guess you can submit driver for attestation signing at any time.
Or is there something you need to wait for?

Just people time to do the signing and test the changes before doing a build.

Took care of it already - `3.1.24305.0` has the updated driver 👍