HardwareDevices: Smart data for NVMe drives
winsiderss/systeminformer pull request #2266
Opened 2024-11-02 20:07 UTC by ge0rdi

Code based on:
https://learn.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices#example-nvme-get-log-pages-query

Description of SMART NVMe attributes:
https://en.wikipedia.org/wiki/Self-Monitoring,_Analysis_and_Reporting_Technology#Known_NVMe_S.M.A.R.T._attributes

How it looks like:
![image](https://github.com/user-attachments/assets/83baba45-8481-4472-af31-c14177bbb124)

2024-11-03 19:18 UTC, jxy-s approved these changes

2024-11-03 22:46 UTC, jxy-s requested changes
Should probably hide the irrelevant columns when displaying the NVME SMART data (`Best`, `Raw`, `Raw (Hex)`,...)?

2024-11-03 22:46 UTC, jxy-s commented on plugins/HardwareDevices/diskdetails.c
> +VOID AddNvmeSmartEntry(HWND ListViewHandle, LPCWSTR Name, PPH_STRING Value)
```suggestion
VOID AddNvmeSmartEntry(
    _In_ HWND ListViewHandle, 
    _In_ LPCWSTR Name, 
    _In_ PPH_STRING Value
    )
```

2024-11-03 22:46 UTC, jxy-s commented on plugins/HardwareDevices/diskdetails.c
> +    );
```suggestion
        );
```

2024-11-03 22:46 UTC, jxy-s commented on plugins/HardwareDevices/diskdetails.c
> +    );
```suggestion
        );
```

2024-11-03 22:46 UTC, jxy-s commented on plugins/HardwareDevices/storage.c
> +    );
```suggestion
        );
```

2024-11-04 07:43 UTC, ge0rdi commented
> Should probably hide the irrelevant columns when displaying the NVME SMART data (Best, Raw, Raw (Hex),...)?

That would be great.
Unfortunately, hiding/deleting columns seems to interfere with saving column widths.
So in case if you have mix of NVMe and non-NVMe drives, column widths for `Best`/`Raw`/etc  won't get saved (if you have displayed Smart properties for NVMe drive).

2024-11-04 22:52 UTC, jxy-s approved these changes

2024-11-04 23:04 UTC, merged